import type { Metadata } from "next";
import "./globals.css";
import { Anta, Antic, Anton_SC } from "next/font/google";

import Navbar from "./components/Navbar";


const anta = Anta({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anta",
});

const antic = Antic({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-antic",
});

const anton = Anton_SC({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${anta.variable} ${antic.variable} ${anton.variable} antialiased`}
    >
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
