import type { Metadata } from "next";
import "./globals.css";
import { Anta, Antic, Anton_SC } from "next/font/google";
import Navbar from "./components/Navbar";

const anta = Anta({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anta",
});
const antic = Antic({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-antic",
});
const anton = Anton_SC({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Bryan Fernando | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${anta.variable} ${antic.variable} ${anton.variable} antialiased`}
    >
      <body>
        {/* Fixed background with -z-10 */}
        <Navbar />
        <main className="relative z-20">{children}</main>
      </body>
    </html>
  );
}
